const loveReasons = [
  "I Love you ❤️",
  "You make me smile every day ❤️",
  "Your kindness melts my heart 😊",
  "You support me no matter what 💪",
  "I love how you laugh at my jokes 😆",
  "You're my safe place 💖",
  "You have the most beautiful soul 🌟",
  "You're my best friend and my love 🥰",
  "You inspire me to be better 🔥",
  "You make life an adventure 🌍",
  "I can't imagine life without you 💞",
  "You always know how to cheer me up 💕",
  "You listen to me even when I ramble 🎧",
  "Your hugs feel like home 🤗",
  "You believe in me when I doubt myself 🌠",
  "Your love makes my world brighter ☀️",
  "You make even the simplest moments special ✨",
  "You're my biggest blessing 🙏",
  "You understand me like no one else 🤍",
  "Your patience is endless with me 🕊️",
  "I love how we can talk about anything 💬",
  "You make my heart race with just one look 😍",
  "Your love makes me a better person 💗",
  "I love the way you say my name 🥹",
  "You make ordinary days feel magical ✨",
  "Your laugh is my favorite sound 🎶",
  "You're the reason I believe in love 💓",
  "I love the way you hold my hand 🤝",
  "You make me feel like the luckiest person alive 🍀",
  "You're always there when I need you 🛡️",
  "Your heart is the most beautiful thing about you ❤️",
  "I fall in love with you more every day 🌹",
  "You see the best in me, even when I don't 🪄",
  "I love how we can be silly together 🤪",
  "Your voice is my comfort song 🎵",
  "You love me for who I am, flaws and all 🌸",
  "You're my favorite person in the entire world 🌎",
  "Your cuddles are the best therapy 🤗",
  "You make love feel so effortless 💞",
  "You make even bad days feel okay 🌈",
  "You are my forever and always 💍",
  "I love the way you look at me 🥰",
  "You're my best decision ever made 💖",
  "With you, every moment is a memory 📸",
  "Your happiness is my happiness too 😊",
  "I love growing and learning with you 📖",
  "You bring light to my darkest days 🕯️",
  "No one makes me feel the way you do 💘",
  "You're the dream I never want to wake up from 🌙",
  "You complete me in every way 💫",
  "I will love you now and forevermore 🕰️",
];

export default loveReasons;
